spring:
  application:
    name: unibank_api
  datasource:
    url: jdbc:mysql://localhost:3306/uni_bank?allowPublicKeyRetrieval=true&useSSL=false
    username: uni_bank
    password: Unibank@123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        type: DEBUG
        jdbc:
          time_zone: UTC