spring:
  application:
    name: unibank_api
  datasource:
    url: jdbc:mysql://localhost:3306/uni_bank?allowPublicKeyRetrieval=true&useSSL=false
    username: uni_bank
    password: Unibank@123
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet.context-path: /api
  port: 9000

unibank:
  jwtSecretKey: f79a15602a60f23efc43615810e58ce8a3f7a703724a634725bef9e84ddcdc29
  jwtExpirationMs: 3600000